spring:
  profiles.active: dev

  application.name: "Demo APP"

  threads.virtual.enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/demo
    user: admin
    password: admin
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      jdbc:
        time_zone: UTC
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy