server:
  shutdown: graceful
  compression:
    enabled: true

application:
  rate-limit:
    account:
      capacity: 10
      refillRate: 2
      timeInMinutes: 1
    client:
      capacity: 15
      refillRate: 1
      timeInMinutes: 2
  scheduled:
    #Every 15 seconds starting at :00 second after the minute
    clean: "-" #"0/15 * * ? * *"

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    correlation: "[trace-id=%X{trace-id}]"

spring:
  profiles.active: @spring.profiles.active@

  lifecycle.timeout-per-shutdown-phase: 30s

  application.name: "Demo APP"

  threads.virtual.enabled: true

  task:
    # Pool de tareas de @Async
    execution:
      thread-name-prefix: "async-virtual-"
      threads:
        virtual:
          enabled: true
    # Pool de tareas de @Scheduled
    scheduling:
      thread-name-prefix: "schedule-virtual-"
      threads:
        virtual:
          enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/demo
    user: admin
    password: admin
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  data:
    jpa:
      open-in-view: false
      repositories:
        bootstrap-mode: deferred
      properties:
        jdbc:
          time_zone: UTC
          database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always
    mappings:
      access: none

featureflag:
  audit:
    dynamo: false   # true para usar DynamoDB

aws:
  dynamodb:
    endpoint: http://localhost:8000   # Usa esto si es DynamoDB Local, deja vacío si es AWS real
    region: us-east-1
    tableName: RateLimitEventAudit
